---
title: "explo"
author: "Claire"
date: "2024-01-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Exploratory analysis

## On US data sample
```{r install}

#### INSTALLATION AND PACKAGES ####
# cran release
if (!require("auk")) {
install.packages("auk")
library(auk)
}

if (!require("dplyr")) {  
install.packages("dplyr")
library(dplyr)
}

# or install the development version from github
#if (!require("remotes")) {
#  install.packages("remotes")
#  library(remotes)
#  remotes::install_github("CornellLabofOrnithology/auk")
#}
```

```{r filepaths}
folder <- "/data/ebd_US-AL-101_202204_202204_relApr-2022_SAMPLE/"
filename <- 'ebd_US-AL-101_202204_202204_relApr-2022.txt'
file <- paste0(getwd(),paste0(folder, filename)) 
path <- paste0(getwd(),folder)
```

```{r setup}
library(auk)
library(lubridate)
library(sf)
library(gridExtra)
library(tidyverse)
library(dplyr)
library(leaflet)
# resolve namespace conflicts
select <- dplyr::select

#ebd <- read_ebd(file) 
#glimpse(ebd)
``` 

```{r select}
ebd_filtered <- ebd %>% select(checklist_id, category, common_name, scientific_name,observation_count, state, bcr_code, latitude, longitude, observation_date, observer_id, protocol_type, approved,reviewed)
```


## On French data 2015-2024



```{r filepaths2}
folder <- "/data/ebd_FR_201501_202401_smp_relNov-2023/"
filename <- 'ebd_FR_201501_202401_smp_relNov-2023.txt'
file <- paste0(getwd(),paste0(folder, filename)) 
path <- paste0(getwd(),folder)
```

```{r setup2}
library(auk)
library(lubridate)
library(sf)
library(gridExtra)
library(tidyverse)
library(dplyr)
# resolve namespace conflicts
select <- dplyr::select

#ebd_fr <- read_ebd(file) 
#glimpse(ebd_fr)
``` 

```{r select2}
ebd_filtered <- ebd_fr %>% select(checklist_id, category, common_name, scientific_name,observation_count, state, bcr_code, latitude, longitude, observation_date, observer_id, protocol_type, approved,reviewed, time_observations_started, duration_minutes)
```


```{r}
# function to convert time observation to hours since midnight
time_to_decimal <- function(x) {
  x <- hms(x, quiet = TRUE)
  hour(x) + minute(x) / 60 + second(x) / 3600
}

# clean up variables
ebd_filtered <- ebd_filtered |> 
  mutate(
    # convert time to decimal hours since midnight
    hours_of_day = time_to_decimal(time_observations_started),
    # split date into year and day of year
    year = year(observation_date),
    day_of_year = yday(observation_date),
    month = month(observation_date)
  )
```

```{r}
ebd_filtered <- ebd_filtered %>% left_join(ebd_filtered %>% group_by(checklist_id)  %>% summarize(species_observed = sum(as.numeric(observation_count), na.rm = TRUE)) %>% ungroup(), by= 'checklist_id')
```

```{r}
# summarize data by hourly bins
breaks <- seq(0, 24)
labels <- breaks[-length(breaks)] + diff(breaks) / 2
checklists_time <- ebd_filtered |> 
  mutate(hour_bins = cut(hours_of_day, 
                         breaks = breaks, 
                         labels = labels,
                         include.lowest = TRUE),
         hour_bins = as.numeric(as.character(hour_bins))) |> 
  group_by(hour_bins) |> 
  summarise(n_checklists = n(),
            n_detected = sum(as.numeric(species_observed)),
            det_freq = mean(as.numeric(species_observed)))

# histogram
g_tod_hist <- ggplot(checklists_time) +
  aes(x = hour_bins, y = n_checklists) +
  geom_segment(aes(xend = hour_bins, y = 0, yend = n_checklists),
               color = "grey50") +
  geom_point() +
  scale_x_continuous(breaks = seq(0, 24, by = 3), limits = c(0, 24)) +
  scale_y_continuous(labels = scales::comma) +
  labs(x = "Hours since midnight",
       y = "# checklists",
       title = "Distribution of observation start times")

# frequency of detection
g_tod_freq <- ggplot(checklists_time |> filter(n_checklists > 100)) +
  aes(x = hour_bins, y = det_freq) +
  geom_line() +
  geom_point() +
  scale_x_continuous(breaks = seq(0, 24, by = 3), limits = c(0, 24)) +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "Hours since midnight",
       y = "% checklists with detections",
       title = "Detection frequency")

# combine
grid.arrange(g_tod_hist, g_tod_freq)
```


```{r}
write_csv(ebd_filtered, "data/preprocessed_1.csv", na = "")
```

```{r}
ebd_filtered <- read.csv('data/preprocessed_1.csv')
```

```{r}
ebd_small <- ebd_filtered[,c('common_name','observation_count','state','latitude','longitude','observation_date','year','species_observed')]
write_csv(ebd_small, "data/preprocessed_2.csv", na = "")
```

```{r}
summary(ebd_filtered)
```


```{r}
# for loading our data
library(jsonlite)
library(rgdal)
library(sf)
# for plotting
library(extrafont)
library(ggplot2)
library(ggspatial)
library(patchwork)
library(scico)
# for data wrangling
library(dplyr)
```

```{r}
head(ebd_filtered)
```
```{r}
input <- {}
input$year <- 2020
input$state <- 'Occitanie'
input$display <- 'All species'
```
```{r}
input$display <- 'Mallard'
```


```{r}
if (input$year != "All Years") {
  df <- subset(ebd_filtered, year == input$year)
}
if (input$state != "All States") {
  df <- subset(df, state == input$state)
}



if(input$display == "All species") {
  tmp <- df %>% group_by(common_name) %>% summarize(detection = mean(as.numeric(species_observed)), lng = median(longitude), lat = median(latitude))
  m <- leaflet(data = df) %>%
  addTiles() %>% 
  setView(lng = mean(tmp$lng), lat = mean(tmp$lat), zoom = 8)
  pal <- colorQuantile("YlOrRd", tmp$detection, n = 4)
  m <- addCircleMarkers(m, ~longitude, ~latitude, 
                        color = ~pal(tmp$detection),
                        radius = 5,  
                        fillOpacity = 0.5,
                        popup =  ~paste(paste(paste("Observation counts", round(tmp$detection, 2)), 'Species'), tmp$common_name))
  m %>% addLegend(data = tmp,
    pal = pal,
    values = ~detection,
    position = "bottomleft",
    title = "Detection counts:",
    opacity = 0.9
  ) 
  
} else {
  # data 
  tmp <- df %>% subset(common_name == input$display)  # %>% group_by(latitude, longitude) %>% summarize(observation_count = sum(as.numeric(observation_count), na.rm = TRUE))
  tmp$observation_count[tmp$observation_count == 'X'] <- mean(tmp$observation_count, na.rm = TRUE)
  tmp$observation_count <- as.numeric(tmp$observation_count)
  tmp$observation_count[is.na(tmp$observation_count)] <- mean(tmp$observation_count, na.rm = TRUE)
  # map 
  m <- leaflet(data = tmp) %>%
  addTiles() %>%
  setView(lng = mean(tmp$longitude), lat = mean(tmp$latitude), zoom = 5)
  pal <- colorBin("YlOrRd", tmp$observation_count, 3)
  m <- addCircleMarkers(m, ~tmp$longitude, ~tmp$latitude, 
                        color = ~pal(tmp$observation_count),
                        radius = 3, 
                        fillOpacity = 0.5,
                        popup = ~paste("Observation counts", round(as.numeric(tmp$observation_count, na.rm = TRUE), 2))
  )
  
}


```


```{r}
ebd_filtered <- read.csv('/Users/clairehe/Documents/GitHub/auk/RShiny_app/data/preprocessed_2.csv')

```


```{r}
length(unique(ebd_s$state))

```
```{r}
input <- {}
input$year <- 'All Years'
input$state <- 'All States'
input$display <- 'Eurasian Kestrel'
```

```{r}
if (input$year != "All Years") {
  df <- subset(df, year == input$year)
} 

if (input$state != "All States") {
  df <- subset(df, state == input$state)
} 

if(input$year == "All Years"){
  df <- df %>% group_by(common_name, latitude, longitude) %>% summarize(species_observed = mean(as.numeric(species_observed)), observation_count = mean(as.numeric(observation_count)))
}

if (input$display == "All species") {
  tmp <- df %>% group_by(common_name) %>% summarize(detection = mean(as.numeric(species_observed)), lng = median(longitude), lat = median(latitude))
  m <- leaflet(data = df) %>%
  addTiles() %>% 
  setView(lng = mean(tmp$lng), lat = mean(tmp$lat), zoom = 8)
  pal <- colorQuantile("YlOrRd", tmp$detection, n = 4)
  m <- addCircleMarkers(m, ~longitude, ~latitude, 
                        color = ~pal(tmp$detection),
                        radius = 5, 
                        fillOpacity = 0.5,
                        popup =  ~paste(paste(paste("Observation counts", round(tmp$detection, 2)), 'Species'), tmp$common_name))
  m %>% addLegend(data = tmp,
    pal = pal,
    values = ~detection,
    position = "bottomleft",
    title = "Detection counts:",
    opacity = 0.9
  ) 
  
} else {
  # data 
  tmp <- df %>% subset(common_name == input$display)  # %>% group_by(latitude, longitude) %>% summarize(observation_count = sum(as.numeric(observation_count), na.rm = TRUE))
  tmp$observation_count[tmp$observation_count == 'X'] <- mean(tmp$observation_count, na.rm = TRUE)
  tmp$observation_count <- as.numeric(tmp$observation_count)
  tmp$observation_count[is.na(tmp$observation_count)] <- mean(tmp$observation_count, na.rm = TRUE)
  # map 
  m <- leaflet(data = tmp) %>%
  addTiles() %>%
  setView(lng = mean(tmp$longitude), lat = mean(tmp$latitude), zoom = 5)
  pal <- colorBin("YlOrRd", tmp$observation_count, 3)
  m <- addCircleMarkers(m, ~tmp$longitude, ~tmp$latitude, 
                        color = ~pal(tmp$observation_count),
                        radius = 3, 
                        fillOpacity = 0.5,
                        popup = ~paste("Observation counts", round(as.numeric(tmp$observation_count, na.rm = TRUE), 2))
  )
}
```

